LnF/urls.py
from django.urls import path
from LnF import views

app_name = "LnF"

urlpatterns = [
    path("", view=views.list, name='list'),
    path("new/", view=views.new, name='new'),
    path("new/<int:pk>", view=views.new_one, name='new_one'),
    path("tag/", view=views.tag, name='tag'),
    path("<int:pk>/booth_detail/", view=views.booth_detail, name='booth_detail'),
    path("<int:pk>/post_detail/", view=views.post_detail, name='post_detail'),
    path("<int:pk>/update/", view=views.post_update, name='post_update'),
    path("<int:pk>/delete/", view=views.post_delete, name='post_delete'),
    path("<int:pk>/post_detail/add_comment/", view= views.add_comment, name="add_comment"),
    path("<int:pk>/post_detail/del_comment/", view= views.del_comment, name="del_comment"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brand.urls')),
    path('find/', include('map.urls')),
    path('user/', include('user.urls')),
    path('LnF/', include('LnF.urls')),
    path('accounts/', include('allauth.urls')),

    path('', include('django.contrib.auth.urls')),
    
    #템플릿 추가중
    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='user/reset_password.html'),
        name='password_reset'
    ),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='user/reset_password_sent.html'), name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='user/reset_password_form.html'),
        name='password_reset_confirm'
    ),

    path(
        'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='user/reset_password_sucess.html'),
        name='password_reset_complete'
    ),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),

]
#set image urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

map/urls.py
from django.urls import path
from map import views

app_name = "map"

urlpatterns = [
    path('booth/review/create/<int:pk>', view=views.booth_review_create, name='booth_review_create'),  # 리뷰 작성/수정 페이지
    path('<int:pk>/update', view=views.review_update, name='review_update'),
    path('<int:pk>/delete', view=views.review_delete, name='review_delete'),

    path('booth/detail/<int:pk>', view=views.booth_detail, name='booth_detail'),
    path('booth/detail/<int:pk>/review', view=views.booth_review_list, name='booth_review_list'),
    path('booth/detail/<int:pk>/like_ajax/', views.like_ajax, name='like_ajax'),
    path('booth/detail/<int:pk>/dislike_ajax/', views.dislike_ajax, name='dislike_ajax'),

    path('', view= views.mainpage, name = 'main'), # 메인페이지 view
    path('map/', views.mymap, name="mymap"),
    path('search/', views.search, name="search"),
    path('map/load/', view=views.load, name='load')
]

user/urls.py
from django.urls import path
from . import views

# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "user"

urlpatterns = [
    path("", views.main, name="main"),
    path("my_lnf/", views.my_lnf, name="my_lnf"),
    path('read_my_lnf/<int:pk>', views.read_my_lnf, name="read_my_lnf"),
    path("my_review/", views.my_review, name="my_review"),
    path('read_my_review/<int:pk>', views.read_my_review, name="read_my_review"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="log_out"),
    path("signup/", views.signup, name="signup"),
    path("change_password/", views.change_password, name='change_password'),
    path('modify/', views.modify, name='modify'),

    path('delete/', views.delete, name='delete'),
    path('notice/', views.notice, name="notice"),
    path('readnotice/<int:pk>', views.read_notice, name="read_notice"),
    path('notice/deletenotice/', views.delete_notice, name="delete_notice"),
    path('nav_notice/', views.nav_notice, name="nav_notice"),
]

map/models.py
from django.db import models
from brand.models import Brand
from user.models import User
from datetime import datetime, timedelta
from django.utils import timezone
from multiselectfield import MultiSelectField
from django.core.validators import MaxValueValidator, MinValueValidator
 # Create your models here.

# 부스 이름, 부스 종류, 부스 주소, 부스 운영시간, 부스 브랜드
class Booth(models.Model):
    name = models.CharField(max_length=100)
    location = models.TextField()
    operationHour = models.CharField(max_length=50)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    user = models.ManyToManyField(User, through='Liked', through_fields=('booth', 'user'))
    # 좌표
    x = models.CharField(max_length=50)
    y = models.CharField(max_length=50)

    ## 리뷰로 받는 것들
    street = models.IntegerField(default=0) # 길거리인지(0), 매장인지(1)
    deco = models.CharField(max_length=50) # 소품 (없 0 있 1)
    iron = models.IntegerField(default=0) # 고데기 (없 0 있 1)
    boxnum = models.IntegerField(default=0) # 부스 갯수 (갯수마다)

    rate_average = models.FloatField(default=0) # 별점, 기본값은 0, 별점은 0.5 부터 0.5 단위로?
    likenum = models.IntegerField(default=0) # 이 매장의 좋아요
    review_number = models.IntegerField(default=0)

    def __str__(self):
        return self.name

# user - liked - booth 다 대 다 연결
class Liked(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dolike = models.BooleanField(default = False)
    booth = models.ForeignKey(Booth, on_delete=models.CASCADE)

# 리뷰 작성할 부스, 리뷰 작성하는 user, title, 리뷰 작성한 시간, 사진, 별점
# tag 추가해야

class Review(models.Model):

    TAG_CHOICES = (
        ('시설이 깨끗해요','시설이 깨끗해요'),
        ('소품이 다양해요','소품이 다양해요'),
        ('부스가 많아요','부스가 많아요'),
        ('고데기가 있어요','고데기가 있어요'),
        ('로드점이에요','로드점이에요'),
    )
    COLOR_CHOICES = (
        ('핑크','핑크'),
        ('하늘','하늘'),
        ('노랑','노랑'),
        ('회색','회색'),
        ('남색','남색'),
        ('연두','연두'),
        ('보라', '보라'),
        ('빨강', '빨강'),
        ('주황', '주황'),
        ('기타', '기타'),
    )

    booth = models.ForeignKey(Booth, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(default=datetime.now, blank=True)
    content = models.TextField()
    img = models.ImageField(blank=True, null=True, upload_to="Review")

    boothid = models.IntegerField()
    rate = models.IntegerField(default=0,
                               validators=[
                                   MaxValueValidator(5),
                                   MinValueValidator(0),
                               ]
                               )
    tag = MultiSelectField(choices = TAG_CHOICES)
    color = MultiSelectField(choices = COLOR_CHOICES)

    @property
    def getWidth(self):
        return self.rate*20

    @property
    def timeString(self):
        now = timezone.now() - self.time
        if now < timedelta(minutes=1):
            return '방금 전'
        elif now < timedelta(hours=1):
            return str(int(now.seconds / 60)) + '분 전'
        elif now < timedelta(days=1):
            return str(int(now.seconds / 3600)) + '시간 전'
        elif now < timedelta(days=7):
            now = timezone.now().date() - self.time.date()
            return str(now.days) + '일 전'
        else:
            return False

map/forms.py
from django import forms
from .models import Review
from django.core.exceptions import ValidationError

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        
        fields = ('tag', 'color', 'content', 'img')

    def checkstar(self, request):
        if (request.get('rating')==None):
            self.errors["Rate"]= "\n필수 항목입니다."

map/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReviewForm
from .models import *
from LnF.models import LnF_Post
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings

# Create your views here.
def mainpage(request):
    return render(request, 'base.html')

def mymap(request):
    booths = Booth.objects.all()
    ctx = {'booths': booths, 'API_KEY': settings.KAKAO_APP_KEY} # 너무 많으면 여기서 booths[:10] 로 몇개만 뽑아도 됨!
    return render(request, 'map/mymap.html', context=ctx)

# 부스 평균 별점 계산 후 booth.rate_average 저장
def save_booth_rate_avg(booth): 
    reviews = Review.objects.filter(booth = booth.id)
    
    review_num=len(reviews)
    rate_sum =0
    if review_num == 0:
        booth.rate_average = 0
    else:
        for review in reviews:
            rate_sum += review.rate
        booth.rate_average = round(rate_sum/review_num, 1)
    booth.save()

def tag_count(pk):
    booth = Booth.objects.get(id=pk)  # id가 pk인 게시물 하나를 가져온다.
    reviews = Review.objects.filter(booth = booth.pk)
    tag_list = [['clean', 0], ['prop', 0], ['booth', 0], ['iron', 0], ['street', 0]]

    for review in reviews:
        tags = []
        tags = review.tag
        for tag in tags:
            if tag == '시설이 깨끗해요':
                tag_list[0][1] += 1
            elif tag == '소품이 다양해요':
                tag_list[1][1] += 1
            elif tag == '부스가 많아요':
                tag_list[2][1] += 1
            elif tag == '고데기가 있어요':
                tag_list[3][1] += 1
            elif tag == '로드점이에요':
                tag_list[4][1] += 1
    tag_list = sorted(tag_list, key= lambda x: -x[1])
    return tag_list

def booth_detail(request,pk):
    booth = Booth.objects.get(id=pk)
    reviews = Review.objects.filter(booth = booth.pk).order_by('-time')[:3]
    lnfs = LnF_Post.objects.filter(booth= booth.pk).order_by('-time')
    lnf_num = len(lnfs)
    lnfs = lnfs[:3]

    if request.user.is_authenticated:
        try:
            liked = Liked.objects.get(user = request.user, booth= booth)
            currentLikeState = liked.dolike
        except Liked.DoesNotExist:
            currentLikeState = False
    else:
        currentLikeState = False

    tag_list = tag_count(pk)
    width = booth.rate_average * 20 
    

    ctx = {'booth': booth, 'lnfs' : lnfs, 'reviews': reviews, 'tag_list': tag_list, 'currentLikeState': currentLikeState, 'width':width}
    return render(request, template_name='map/booth_detail.html', context=locals())

def booth_review_list(request,pk):
    booth = Booth.objects.get(id=pk)
    reviews = Review.objects.filter(booth = booth.pk).order_by('-time')
    ctx = {'reviews': reviews,'pk': pk, 'booth':booth, 'boothname': booth.name, }
    return render(request, template_name='map/review_list.html', context=ctx)

@login_required
def booth_review_create(request, pk):
    booth = get_object_or_404(Booth, id=pk)
    boothname = booth.name
    id = pk
    
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        form.checkstar(request.POST)
        
        if form.is_valid():
            rate = request.POST.get('rating')

            post = form.save(commit=False)
            post.booth = booth
            post.user = request.user
            post.boothid = pk
            post.rate = rate
            booth.review_number += 1

            post.save()
            booth.save()
            save_booth_rate_avg(booth)
            return redirect('map:booth_review_list', post.boothid)
    else:
        form = ReviewForm()

    ctx = {'form': form, 'id': id, 'boothname':boothname}
    return render(request, template_name='map/review_create.html', context=ctx)

@login_required
def review_update(request, pk):
    review = get_object_or_404(Review, id=pk)
    boothname = review.booth
    boothid = review.boothid

    if request.user == review.user:
        if request.method == 'POST': #post방식 요청
            form = ReviewForm(request.POST, request.FILES, instance=review)
            if form.is_valid(): #폼 유효하면
                form.checkstar(request.POST)
                rate = request.POST.get('rating')

                review = form.save(commit=False) #데이터 가져오기
                review.rate = rate
                review.save() #저장
                save_booth_rate_avg(review.booth)
                return redirect('map:booth_review_list', boothid)
            
        else:
            form = ReviewForm(instance=review)
        ctx = {'review': review,'id':boothid, 'boothname' : boothname, 'form':form}
        return render(request, template_name='map/review_create.html', context=ctx)

@login_required
def review_delete(request, pk):
    review = get_object_or_404(Review, id=pk)
    if request.user == review.user:
        booth_id = review.boothid
        booth = get_object_or_404(Booth, id=booth_id)  # id가 pk인 게시물 하나를 가져온다.
        booth.review_number -= 1
        booth.save()
        review.delete()

        save_booth_rate_avg(booth)

        return redirect('map:booth_review_list', booth_id)

def search(request):
    search = request.GET.get('search','')
    boothlist = Booth.objects.filter(name__contains=search)
    ctx = {'booths': boothlist}
    return render(request, 'map/mymap.html', context=ctx)


@csrf_exempt
# login o , currentLikeState: False -> True
def like_ajax(request, pk):
    booth = get_object_or_404(Booth, id=pk)
    user = request.user
    try:
        like = Liked.objects.get(user = request.user, booth=booth)

    except Liked.DoesNotExist:
        like = Liked.objects.create(booth = booth, user = user)
    
    like.dolike = True
    booth.likenum += 1
    like.save()
    booth.save()
    return JsonResponse({'booth_id': booth.id })

# login o, currentLikeState: True -> False
def dislike_ajax(request, pk):
    booth = get_object_or_404(Booth, id=pk)
    like = Liked.objects.get(user = request.user, booth = booth)
    
    like.dolike = False
    booth.likenum -= 1
    like.save()
    booth.save()

    return JsonResponse({'booth_id': booth.id })


def search(request):
    search = request.GET.get('search','')
    boothlist = Booth.objects.filter(name__contains=search)
    ctx = {'booths':boothlist}
    return render(request, 'map/mymap.html', context=ctx)


@csrf_exempt
def load(request):
    booths = list(Booth.objects.values("pk", "name", "location", "x", "y", "rate_average", "likenum", "operationHour", "brand__name", "review_number"))
    return JsonResponse({'boothList': booths})

    # [{id, name, location, x, y, rating, likenum, operationHour, brand}, {}]

templates/map/booth_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<script defer type="text/javascript" src="{% static 'js/map/like.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/map/boothdetail.css' %}"> 
{% endblock %}

{% block header %}
<!-- 매장찾기 파란글씨 헤더? 원래 헤더 없애고? -->
{% endblock %}


{% block content %}

    <div id="boothdetail__image">
        {% if booth.brand.name == "하루필름" %}
            <img class="boothdetail__profile" src = "{% static 'icons/profile/haru_profile.png' %}"> </img>
        {% elif booth.brand.name == "인생네컷" %}
            <img class="boothdetail__profile" src = "{% static 'icons/profile/life_profile.png' %}"/></img> 
        {% elif booth.brand.name == "포토이즘박스" %}
            <img class="boothdetail__profile" src = "{% static 'icons/profile/photo_profile.png' %}"/> </img>
        {% elif booth.brand.name == "셀픽스" %}
            <img class="boothdetail__profile" src = "{% static 'icons/profile/selpix_profile.png' %}"/></img>
        {% elif booth.brand.name == "포토시그니처" %}
            <img class="boothdetail__profile" src = "{% static 'icons/profile/sign_profile.png' %}"/></img>
        {% endif %}
    </div>

    <div id="boothdetail__body"> <!-- div:nthchild (1)-->

        <div id="body__name"> <!-- div:nthchild (0)-->
            <h3 class="text-center mb-3 mx-3" style="font-family: ROKAFSansMedium; font-size: 22px">{{ booth.name }}</h3>
            <h6 class="text-center mx-4 mb-3" style="color: #B0B0B0; font-size: 20px;">{{ booth.location }}</h6>
            <div class="text-center">
                {% if request.user.is_authenticated %}
                <div style="font-family: ROKAFSansMedium; font-size: 16px;" class="text-primary d-flex justify-content-evenly">
                    <a href="{% url 'map:booth_review_create' booth.id %}">리뷰 작성✍🏻</a>
                    <a href="{% url 'LnF:new_one' booth.id %}">분실물 작성✍🏻</a>
                </div>

                    <div id="heart_container">
                        {% if currentLikeState %}
                        <div class="detail__heart" onclick="onClickDislike({{booth.id}})">♥ 여기 매장 좋아요!</div>
                        {% else %}
                        <div class="detail__noheart" onclick="onClickLike({{booth.id}})" >♥ 여기 매장 좋아요!</div>
                        {% endif %}
                    </div>
                {% else %}
                <div style="font-family: ROKAFSansMedium; font-size: 16px; color: #C2C2C2 !important; opacity: 0.5;" class="text-primary d-flex justify-content-evenly">
                    <a onclick = "onClickAlert()">리뷰 작성✍🏻</a>
                    <a onclick = "onClickAlert()">분실물 작성✍🏻</a>
                </div>
                <div class="detail__noheart" onclick="onClickAlert()" >♥ 여기 매장 좋아요!</div>
                {% endif %}
            </div>
            <br>
        </div>

        <div style="background-color: #F9F9F9;" class="p-3">

            <div id="boothdetail__tags">
                <div id="boothdetail__tagtop" class="d-flex mb-2">
                    <h4 class="fw-bold me-1">User Tags<h4>
                    <div style="color: #C6C6C6"> ({{ booth.review_number }})</div>
                </div>
                        
                <div id="boothdetail__taglist" class="mx-3">
                    {% if booth.review_number == 0 %}
                    <div class="boothdetail__noreviews text-center fs-6">
                        아직 작성된 리뷰가 없어요 :(
                    </div>

                    {% else %}
                        {% for tag in tag_list %}
                            {% if tag.1 > 0 %}
                                <div class="position-relative">
                                    <div class="tag__fill" data-reviews="{{ booth.review_number }}" data-num="{{ tag.1 }}"></div>
                                    <div class="tag__container mb-2 py-2 px-3 d-flex justify-content-between">
                                        <div class="tag__name">
                                            {% if tag.0 == 'clean' %} ✨ "시설이 깨끗해요"
                                            {% elif tag.0 == 'prop' %} 🎉 "소품이 다양해요" 
                                            {% elif tag.0 == 'booth' %} 📸 "부스가 많아요"
                                            {% elif tag.0 == 'iron' %} 💇🏻‍♀️ "고데기가 있어요"
                                            {% elif tag.0 == 'street' %} 🛣️ "로드점이에요"
                                            {% endif %}
                                        </div>
                                        <div style="color: #1F52FF">
                                            {{tag.1}}
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        
        <div id="boothdetail__reviews" class="p-3">
            <div class="d-flex justify-content-between">
                <div id="boothdetail__reviewtop" class="d-flex align-items-center">
                    <h4 class="fw-bold me-1">Reviews<h4>
                    <div style="color: #C6C6C6"> ({{ booth.review_number }})</div>
                </div>
                {% if booth.review_number != 0 %}
                <a href="{% url 'map:booth_review_list' booth.id %}" class="fw-bold ">View All ></a>
                {% endif %}
            </div>
            <div id="star__container" class="d-flex justify-content-center" style="font-size: 45px; align-items:center;">
                {% if booth.rate_average != 0 %}
                <div style="font-family: SUIT-BOLD; margin-right: .5rem; font-size: 30px;color: gold;">{{ booth.rate_average }}</div>
                {% endif %}
                <div class="star-rating">
                    <div class="star-rating-fill" style= "width: {{ width }}%;">
                        <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                    </div>
                    <div class="star-rating-base">
                        <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                    </div>
                </div>
            </div>
                
            {% if booth.review_number == 0 %}
                <div class="boothdetail__noreviews text-center fs-6">
                    아직 작성된 리뷰가 없어요 :(
                </div>
            {% else %}
            <div id="boothdetail__reviewlist">
                {% for review in reviews %}
                    <div class="row mx-4 mb-4 py-2 px-1 shadow" style="border-radius: 0.5rem;">
                        <div>
                            {{review.content}}
                        </div>
                        <div class="d-flex justify-content-between" style="color: #A3A3B5">
                            <span>
                                {{review.user.username}}
                            </span>
                            <span>
                                {% if review.time.timeString == False %}
                                    {{review.time|time:'y. m. d.'}}
                                {% else %}
                                    {{review.timeString}}
                                {% endif %}
                            </span>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        </div> 

        <div id="boothdetail__LnF" style="background-color: #F9F9F9;" class="p-3">
            <div class="d-flex justify-content-between mb-2">
                <div id="boothdetail__reviewtop" class="d-flex align-items-center">
                    <h4 class="fw-bold me-1">Lost and Found<h4>
                    <div style="color: #C6C6C6">({{lnf_num}})</div>
                </div>
                {% if lnf_num != 0 %}
                <a href="{% url 'LnF:booth_detail' booth.id %}" class="fw-bold ">View All ></a>
                {% endif %}
            </div>
            {% if lnf_num == 0 %}
                    <div class="boothdetail__noreviews text-center fs-6">
                        아직 작성된 게시글이 없어요 :(
                    </div>
            {% else %}

                {% for lnf in lnfs %}
                <div class="row post shadow mx-4 mb-4 py-2 px-1">
                    <a href="{% url 'LnF:post_detail' lnf.id %}">

                        <div style="height: .5rem;"></div>
                        <!-- post content -->
                        <div class="post_content">
                            <span class="post__{{ lnf.tag }}">{{lnf.tag}}</span>{{lnf.content}}
                        </div>
                        <div style="height: .5rem;"></div>
                        <!-- post footer -->
                        <div class="post__footer">
                            <div>
                                {{lnf.user.username}}<br>
                            </div>
                            <div>
                                {% if lnf.timeString == False %}
                                {{lnf.time|date:'y. m. d.'}}
                                {% else %}
                                {{lnf.timeString}}
                                {% endif %}
                            </div>
                        </div>                
                    </a>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/map/review_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/map/list.css' %}?after">
    <script defer src="{% static 'js/map/imgmodal.js' %}"></script>

{% endblock %}

{% block content %}
<div class = "review">
    <div class="container">

    <div class = 'backbtn item col-2'>
        <button type="button" class=" goback btn"><a href = "{% url 'map:booth_detail' pk %}"> 〈 </a></button>
    </div>

    <div class ='title item col-10'>
        {{boothname}}
    </div>
</div>
        {% for review in reviews %}

        <div class="reviewblock">
            <div class="foot">
                        {{review.user}} | {{review.time|date:'m월 d일'}}
                </div>
            <div class="container-drop">
                    <div class="dropdown">
                        {% if review.user == request.user %}
                  <a class="btn btn-sm btn-outline-none dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">⋮</a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">

                    <li><a class="dropdown-item" href="{% url 'map:review_update' review.id %}">수정</a></li>
                    <li><a class="dropdown-item" onclick="post_del({{post.id}})">삭제</a></li>
                      {% endif %}
                  </ul>
                </div>
                </div>
            <div class="container">

                {% if review.img %}
                <div class="content col-7">
                    <div class="text">
                                    {{review.content}}
                    </div>
                    <div class="color">
                                        <div class ="colortext" style="width:40px">배경색 : </div>
                                        {% for color in review.color %}

                                        {% if color == '핑크'%}<div><button type="button" class="colorbtn colorpink">■</button></div>
                                        {% elif color == '하늘'%}<div><button type="button" class="colorbtn colorskyblue">■</button></div>
                                        {% elif color == '노랑'%}<div><button type="button" class="colorbtn coloryellow">■</button></div>
                                        {% elif color == '회색'%}<div><button type="button" class="colorbtn colorgray">■</button></div>
                                        {% elif color == '남색'%}<div><button type="button" class="colorbtn colorindigo">■</button></div>
                                        {% elif color == '연두'%}<div><button type="button" class="colorbtn colorgreen">■</button></div>
                                        {% elif color == '보라'%}<div><button type="button" class="colorbtn colorpurple">■</button></div>
                                        {% elif color == '빨강'%}<div><button type="button" class="colorbtn colorred">■</button></div>
                                        {% elif color == '주황'%}<div><button type="button" class="colorbtn colororange">■</button></div>
                                        {% elif color == '기타'%}<div><button type="button" class="colorbtn colorrainbow">■</button></div>
                                        {% endif %}
                                        {% endfor %}
                                </div>
                </div>

                <div class="imgcontent col-5">
                    <img src="{{ review.img.url }}" class="img" width="100%">
                    <div class="modal">
                      <span class="close"></span>
                      <img src= "{{ review.img.url }}" class="modal-content">
                    </div>
                </div>
                {% else %}
                <div>
                    <div class="text">
                                {{review.content}}
                            </div>
                    <div class="color">
                                    <div class ="colortext" style ="width: 40px">배경색 : </div>
                                    {% for color in review.color %}

                                    {% if color == '핑크'%}<div><button type="button" class="colorpink">■</button></div>
                                    {% elif color == '하늘'%}<div><button type="button" class="colorbtn colorskyblue">■</button></div>
                                    {% elif color == '노랑'%}<div><button type="button" class="colorbtn coloryellow">■</button></div>
                                    {% elif color == '회색'%}<div><button type="button" class="colorbtn colorgray">■</button></div>
                                    {% elif color == '남색'%}<div><button type="button" class="colorbtn colorindigo">■</button></div>
                                    {% elif color == '연두'%}<div><button type="button" class="colorbtn colorgreen">■</button></div>
                                    {% elif color == '보라'%}<div><button type="button" class="colorbtn colorpurple">■</button></div>
                                    {% elif color == '빨강'%}<div><button type="button" class="colorbtn colorred">■</button></div>
                                    {% elif color == '주황'%}<div><button type="button" class="colorbtn colororange">■</button></div>
                                    {% elif color == '기타'%}<div><button type="button" class="colorbtn colorrainbow">■</button></div>
                                    {% endif %}
                                    {% endfor %}
                            </div>
                </div>
                {% endif %}


            </div>

            <div class="container_review">
                    <div class="star-rating">
                        <div class="star-rating-fill" style= "width: {{review.getWidth}}%;">
                            <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                        </div>
                        <div class="star-rating-base">
                            <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                        </div>
                    </div>
            </div>
            <div class = "tag">
                        {% for tag in review.tag %}
                        {% if tag == '시설이 깨끗해요'%}<div class="tagbtn">✨ 시설이 깨끗해요</div>
                        {% elif tag == '소품이 다양해요'%}<div class="tagbtn">🎉  소품이 다양해요</div>
                        {% elif tag == '부스가 많아요'%}<div  class="tagbtn">📸 부스가 많아요</div>
                        {% elif tag == '고데기가 있어요'%}<div class="tagbtn">💇🏻‍ 고데기가 있어요</div>
                        {% elif tag == '로드점이에요'%}<div class="tagbtn">🛣️ 로드점이에요</div>
                        {% endif %}
                        {% endfor %}
            </div>
        </div>

    <script>
        const post_del = (id) => {
        var res = confirm('정말로 삭제하시겠습니까?');
        if (res){
            window.location.href = "{% url 'map:review_delete' review.id %}"
            alert('성공적으로 삭제되었습니다.')
        }
    }
    </script>
        {% endfor %}
        <button type="button" class="write btn btn-secondary"> <a href = "{% url 'map:booth_review_create' booth.id %}"> 리뷰 작성</a></button>
</div>

{% endblock %}