LnF/urls.py
from django.urls import path
from LnF import views

app_name = "LnF"

urlpatterns = [
    path("", view=views.list, name='list'),
    path("new/", view=views.new, name='new'),
    path("new/<int:pk>", view=views.new_one, name='new_one'),
    path("tag/", view=views.tag, name='tag'),
    path("<int:pk>/booth_detail/", view=views.booth_detail, name='booth_detail'),
    path("<int:pk>/post_detail/", view=views.post_detail, name='post_detail'),
    path("<int:pk>/update/", view=views.post_update, name='post_update'),
    path("<int:pk>/delete/", view=views.post_delete, name='post_delete'),
    path("<int:pk>/post_detail/add_comment/", view= views.add_comment, name="add_comment"),
    path("<int:pk>/post_detail/del_comment/", view= views.del_comment, name="del_comment"),
]

brand/urls.py
from django.urls import path
from . import views
app_name = "brand"

urlpatterns = [
    path("", view = views.list, name="list")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brand.urls')),
    path('find/', include('map.urls')),
    path('user/', include('user.urls')),
    path('LnF/', include('LnF.urls')),
    path('accounts/', include('allauth.urls')),

    path('', include('django.contrib.auth.urls')),
    
    #템플릿 추가중
    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='user/reset_password.html'),
        name='password_reset'
    ),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='user/reset_password_sent.html'), name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='user/reset_password_form.html'),
        name='password_reset_confirm'
    ),

    path(
        'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='user/reset_password_sucess.html'),
        name='password_reset_complete'
    ),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),

]
#set image urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "user"

urlpatterns = [
    path("", views.main, name="main"),
    path("my_lnf/", views.my_lnf, name="my_lnf"),
    path('read_my_lnf/<int:pk>', views.read_my_lnf, name="read_my_lnf"),
    path("my_review/", views.my_review, name="my_review"),
    path('read_my_review/<int:pk>', views.read_my_review, name="read_my_review"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="log_out"),
    path("signup/", views.signup, name="signup"),
    path("change_password/", views.change_password, name='change_password'),
    path('modify/', views.modify, name='modify'),

    path('delete/', views.delete, name='delete'),
    path('notice/', views.notice, name="notice"),
    path('readnotice/<int:pk>', views.read_notice, name="read_notice"),
    path('notice/deletenotice/', views.delete_notice, name="delete_notice"),
    path('nav_notice/', views.nav_notice, name="nav_notice"),
]

LnF/models.py
from django.db import models
from map.models import Booth
from user.models import User
from datetime import datetime, timedelta
from django.utils import timezone
from django import forms


# Create your models here.

TAG_CHOICE = (
    ('분실', '분실'),
    ('보관', '보관'),
)

class LnF_Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    booth = models.ForeignKey(Booth, on_delete=models.CASCADE)
    
    img = models.ImageField(blank=True, null=True, upload_to="LnF")
    content = models.TextField()
    tag = models.CharField(max_length=50, choices=TAG_CHOICE)
    
    time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.content
    
    @property
    def timeString(self):
        now = timezone.now() - self.time
        if now < timedelta(minutes=1):
            return '방금 전'
        elif now < timedelta(hours=1):
            return str(int(now.seconds / 60)) + '분 전'
        elif now < timedelta(days=1):
            return str(int(now.seconds / 3600)) + '시간 전'
        elif now < timedelta(days=7):
            now = timezone.now().date() - self.time.date()
            return str(now.days) + '일 전'
        else:
            return False
    @property
    def get_fileName(self):
        filename = self.img.url.split('/')[3]
        return filename




class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(LnF_Post, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    
    content = models.TextField()
    time = models.DateTimeField(default=datetime.now, blank=True)
    
    read = models.IntegerField(default=0)

    @property
    def timeString(self):
        now = timezone.now() - self.time
        if now < timedelta(minutes=1):
            return '방금 전'
        elif now < timedelta(hours=1):
            return str(int(now.seconds / 60)) + '분 전'
        elif now < timedelta(days=1):
            return str(int(now.seconds / 3600)) + '시간 전'
        elif now < timedelta(days=7):
            now = timezone.now().date() - self.time.date()
            return str(now.days) + '일 전'
        else:
            return False

brand/models.py
from django.db import models

# Create your models here.

# o/x -> 0, 1로 해서 구분하면 될듯
# 브랜드명, 재쵤영 여부, 리모컨, 가격, qr 여부
class Brand(models.Model):
    name = models.CharField(max_length=50, unique= True)
    retake = models.CharField(max_length=50)
    remote = models.CharField(max_length=50)
    QR = models.CharField(max_length=50)
    etc = models.TextField(null=True)
    # 촬영 시간
    time = models.CharField(max_length=50)
    img = models.ImageField()
    liked_img = models.ImageField(null=True)

    def __str__(self):
        return self.name



class Frame(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    name = models.CharField(max_length=50)
    # 4cut, 6cut 등
    frame = models.CharField(max_length=50)
    # 촬영take 수
    take = models.IntegerField()
    # 2장 기준
    price = models.IntegerField()
    # 기타 특징
    etc = models.CharField(max_length=200, null=True)


    def __str__(self):
        return self.name

LnF/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class PostForm(forms.ModelForm):
    tag = forms.ChoiceField(widget=forms.RadioSelect, choices=TAG_CHOICE)

    class Meta:
        model = LnF_Post
        fields = ('content', 'img')

LnF/views.py
from cmath import pi
from django.http import  JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
from .forms import *
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from map.models import Booth
from brand.models import Brand
from user.models import User
import json

@csrf_exempt
def list(request):
    if request.method == 'GET':
        query = request.GET.get('query', '')
        if query:
            booths = Booth.objects.filter(name__icontains = query)
            posts = LnF_Post.objects.filter(booth__in = booths).order_by('-time')
        else:
            posts=LnF_Post.objects.all().order_by('-time')
        ctx = {'posts': posts, 'query': query}
        
        return render(request, 'LnF/list.html', context=ctx)

# 얘는 html에서 자체 예외처리 함?
def new(request):
    user = request.user
    booths = Booth.objects.all()

    if request.method == "POST":
        booth_name = request.POST.get('booth')
        tag = request.POST.get('tag')
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = user
            new_post.tag = tag
            new_post.booth = get_object_or_404(Booth, name=booth_name)
            new_post.save()
            return redirect('LnF:list')
    
    else:
        form = PostForm()
    
    ctx = {'form': form, 'booths': booths }
    return render(request, 'LnF/new.html', ctx)

def new_one(request, pk):
    user = request.user
    booth = get_object_or_404(Booth, pk=pk)

    if request.method == "POST":
        tag = request.POST.get('tag')
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = user
            new_post.tag = tag
            new_post.booth = booth
            new_post.save()
            return redirect('LnF:list')
    
    else:
        form = PostForm()
    
    ctx = {'form': form, 'booth': booth }
    return render(request, 'LnF/new.html', ctx)

def tag(request):
    req = json.loads(request.body)


# pk: booth pk
def booth_detail(request, pk):
    booth = get_object_or_404(Booth, id=pk)
    posts = LnF_Post.objects.filter(booth = booth).order_by('-time')
    ctx = {'posts': posts, 'booth': booth}
    return render(request, 'LnF/booth_detail.html', context=ctx)

def post_detail(request,pk):
    post = get_object_or_404(LnF_Post, id=pk)
    booth = post.booth
    ctx = {'post': post, 'booth': booth}
    return render(request, 'LnF/post_detail.html', context=ctx)

@login_required
def post_update(request, pk):
    post = get_object_or_404(LnF_Post, id=pk)
    booths = Booth.objects.all()
    booth = post.booth

    if request.user == post.user:
        if request.method == 'POST':
            booth_name = request.POST.get('booth')
            tag = request.POST.get('tag')
            form = PostForm(request.POST, request.FILES, instance=post)

            if form.is_valid():
                post.booth = get_object_or_404(Booth, name=booth_name)
                post.tag = tag
                post = form.save(commit=False)
                post.save()
                return redirect('LnF:post_detail', pk)

        else:
            # tag=post.tag
            form = PostForm(instance=post)
        ctx = {'form': form, 'booths':booths, 'booth':booth, 'post':post}
        return render(request, 'LnF/new.html', context=ctx)

@login_required
def post_delete(request, pk):
    post = get_object_or_404(LnF_Post, id=pk)
    if request.user == post.user:
        post.delete()
        return redirect('LnF:list')



# ajax
@csrf_exempt
def add_comment(request, pk):
    req = json.loads(request.body)
    id = req['id']
    type = req['type']
    content = req['content']
    
    comment = Comment()
    comment.post = LnF_Post.objects.get(id = id)
    comment.content = content
    comment.user = request.user
    comment.time = timezone.now()
    comment.save()
    comment_id = comment.id

    print(request.user.username)
    return JsonResponse({'id': id, 'type': type, 'content': content, 'comment_id': comment_id, 'user': request.user.username })

@csrf_exempt
def del_comment(request, pk):
    req = json.loads(request.body)
    comment_id = req['id']
    
    comment = get_object_or_404(Comment, id = comment_id)
    comment.delete()
    return JsonResponse({'id': comment_id})

@csrf_exempt
def tag(request):
    req = json.loads(request.body)
    query = req['query']
    postList = []

    if query:
        booths = Booth.objects.filter(name__icontains = query)
        posts = LnF_Post.objects.filter(booth__in = booths).order_by('-time')
    else:
        posts=LnF_Post.objects.all().order_by('-time')

    if req["분실"] == True:
        lostTag = posts.filter(tag = '분실')
        postList += lostTag
    if req["보관"] == True:
        keepTag = posts.filter(tag = "보관")
        postList += keepTag

    resList = []
    for post in postList:
        if post.img:
            img = post.img.url
        else:
            img = ""

        resList.append({'id': post.id, 'booth_name': post.booth.name, 'booth_id': post.booth.id ,'user': post.user.username, 'timeString': post.timeString, 'time': post.time.strftime('%m월 %d일'), 'content': post.content, 'img': img, 'tag': post.tag, 'cntcmt': len(post.comment_set.all())})
    return JsonResponse({'resList': resList})

 

brand/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def list(request):
    brands = Brand.objects.all()

    brand_list = []
    for brand in brands:
        brand_detail = [brand.id, brand.name, brand.retake, brand.remote, brand.time, brand.img]

        etcs = brand.frame_set.all()
        etcList = []
        for etc in etcs:
            etcList.append([etc.price, etc.frame, etc.take])

        brand_detail.append(etcList)

        brand_list.append(brand_detail)
 
        # brand_list = [brand_id, brand_name, retake, remote, time, img, [frame]]
        # frame = [price, 프레임 컷 수, 총 촬영 수]

    ctx = {"brand_list": brand_list}
    return render(request, "brand/main.html", ctx)

templates/brand/LnF/booth_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section>
    <h1>{{ booth.name }}</h1>
    <a href="{% url 'LnF:list' %}">목록으로</a> <br>
    {% for post in posts %}
    <div>
        작성자: {{post.user.username}}<br>
        {% if post.timeString == False %}
            작성시간: {{post.time|date:'m월 d일'}}
        {% else %}
            작성시간: {{post.time}} <br>
            작성시간: {{post.timeString}}
        {% endif %}
        <br>
        태그: {{post.tag}}
        <br>
        내용: {{post.content}}
        <br>
        {% if post.img %}
            <img src="{{ post.img.url }}" alt="" width="auto"> 
        {% endif %}
    </div>
    <br>
    {% endfor %}
</section>

{% endblock %}

templates/brand/LnF/list.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<script defer src="{% static 'js/LnF/filter.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/LnF/style.css' %}"> 
{% endblock %}

{% block content %}
<div class="container">
    <!-- search -->
    <section>
        <div class="container">
            <form class="search" action="" method="get">
                <div class="search__btn">
                    <button type="submit" value="검색">
                        <i class="ri-search-line ri-1x"></i>
                    </button>
                </div>
                <div class="search__input w-100">
                    <input id="query" type="text" name="query" value="{{query}}" placeholder="ex. 잠실">
                </div>
                <div class="search__btn">
                    <button class="search__close" onclick="delInput()">
                        <i class="ri-close-fill ri-1x"></i>
                    </button>
                </div>
            </form>
        </div>
    </section>
    <div class="blank"></div>
    <!-- btn sec -->
    <section>
        <div class="container d-flex justify-content-between" style="width: 100%;">
            <div class="lnf__btn1 d-flex justify-content-center">
                <input type="checkbox" checked name="tag" value="분실" class="btn-check" id="btn-check" autocomplete="off">
                <label class="btn" for="btn-check" style="color: white;"> 잃어버렸어요 :( </label>
            </div>
    
            <div class="lnf__btn2 d-flex justify-content-center">
                <input type="checkbox" checked name="tag" value="보관" class="btn-check" id="btn-check" autocomplete="off">
                <label class="btn" for="btn-check" style="color: white;"> 발견했어요 :) </label>
            </div>
        </div>
    </section>
    <!-- write sec -->
    <section>
        <div class="lnf__write" style="cursor: pointer; z-index: 2; right: 1rem; bottom: 1rem;">
            <a href="{% url 'LnF:new' %}">
                <div class="center" style="border-radius: 50%; width: 60px; height: 60px; background-color:#1F52FF;; color:white">
                    <i class="ri-pencil-fill ri-2x"></i>
                </div>
            </a>
        </div>
    </section>
    <!-- post sec -->
    <section id="postList">
        <div class="container d-flex flex-column">
            {% for post in posts %}
            <div class="post shadow p-3">
                <!-- post title -->
                <div class="post__title">
                    <span class="post__{{ post.tag }}">{{post.tag}}</span>
                    <a href="{% url 'LnF:post_detail' post.id %}">{{post.booth.name}}</a>
                </div>
                <div style="height: .5rem;"></div>
                <!-- post content -->
                <div class="post_content">
                    {{post.content}} <br>
                    {% if post.img %}
                        <img src="{{ post.img.url }}" alt="" width="300"> 
                    {% endif %}
                </div>
                <div style="height: .5rem;"></div>
                <!-- post footer -->
                <div class="post__footer">
                    <div>
                        {{post.user.username}}<br>
                    </div>
                    <div>
                        {% if post.timeString == False %}
                        {{post.time|date:'m월 d일'}}
                        {% else %}
                        {{post.timeString}}
                        {% endif %}
                    </div>
                </div>                
            </div>
        {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

templates/brand/LnF/new.html
 {% extends 'base.html' %}
<!-- main block -->
{% block content %}

{% if user.is_authenticated %}
        <h1>New POST</h1>
        <form method="POST"  enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tr>
                    <th><label for="id_booth">Booth:</label></th>
                    <td>
                        <input type="text" name="booth" value="{{booth}}" list="boothList" placeholder="매장 이름을 입력하세요.">
                        <datalist id = "boothList">
                            {% for booth in booths %}
                                <option value="{{booth.name}}"></option>
                            {% endfor %}
                        </datalist>
                    </td>
                </tr>
                {{form.as_table}}
            </table>
            <button type = 'submit'>Submit</button>
        </form>
    {% else %}
        <script type="text/javascript">
            alert('로그인을 먼저 해주세요!')
            window.location.href = '{% url "user:login" %}'
        </script>
    {% endif %}
{% endblock %}

templates/brand/LnF/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head%}
<script defer src="{% static 'js/LnF/comment.js' %}"></script>
{% endblock %}

{% block content %}
<section>
    <h1><a href="{% url 'LnF:booth_detail' booth.id %}">{{ booth.name }}</a></h1>
    <a href="{% url 'LnF:list' %}">목록으로</a> <br>
    <div>
        작성자: {{post.user.username}}<br>
        {% if post.timeString == False %}
            작성시간: {{post.time|date:'m월 d일'}}
        {% else %}
            작성시간: {{post.time}} <br>
            작성시간: {{post.timeString}}
        {% endif %}
        <br>
        태그: {{post.tag}}
        <br>
        내용: {{post.content}}
        <br>
        {% if post.img %}
            <img src="{{ post.img.url }}" alt="" width="auto"> 
        {% endif %}
        {% if post.user == request.user %}
            <a href="{% url 'LnF:post_update' post.id %}">수정</a>
            <!-- <a href="{% url 'LnF:post_delete' post.id %}">삭제</a> -->
            <button class="button" onclick="post_del({{post.id}})">삭제</button>
        {% endif %}
    </div>
        <!-- 댓글 -->
    <div>
        <h6>댓글</h6>
        <table id="comment-table-{{post.id}}">
            {% for comment in post.comment_set.all %}
            <tr id = "comment-{{comment.id}}">
                <td>댓글내용: {{comment.content}}</td>
                <td>댓글 작성자: {{comment.user}}</td>
                <td>
                    {% if comment.timeString == False %}
                    작성시간: {{comment.time|date:'m월 d일'}}
                    {% else %}
                    작성시간: {{comment.timeString}}
                    {% endif %}
                </td>
                <td>
                    {% if comment.user == request.user %}
                    <button class="del-btn" onclick="onClickDel({{comment.id}})">삭제</button>
                    {% endif %}                    
                </td>
            </tr>
            {% endfor %}
        </table>
        {% if user.is_authenticated %}
        <div>
            <input id="comment_input-{{post.id}}" placeholder="댓글 달기..." type="text"/>
            <button class="btn" onclick="onClickComment({{post.id}}, 'add')">게시</button>
        </div>
        {% else %}
        <input id="comment_input-{{post.id}}" placeholder="로그인 먼저해주세요!" type="text"/>
        {% endif %}
    </div>
        <br>
</section>
<script>
    const post_del = (id) => {
        var res = confirm('정말로 삭제하시겠습니까?');
        if (res){
            window.location.href = "{% url 'LnF:post_delete' post.id %}"
            alert('성공적으로 삭제되었습니다.')
        }
    }
</script>
{% endblock %}