LnF/urls.py
from django.urls import path
from LnF import views

app_name = "LnF"

urlpatterns = [
    path("", view=views.list, name='list'),
    path("new/", view=views.new, name='new'),
    path("new/<int:pk>", view=views.new_one, name='new_one'),
    path("tag/", view=views.tag, name='tag'),
    path("<int:pk>/booth_detail/", view=views.booth_detail, name='booth_detail'),
    path("<int:pk>/post_detail/", view=views.post_detail, name='post_detail'),
    path("<int:pk>/update/", view=views.post_update, name='post_update'),
    path("<int:pk>/delete/", view=views.post_delete, name='post_delete'),
    path("<int:pk>/post_detail/add_comment/", view= views.add_comment, name="add_comment"),
    path("<int:pk>/post_detail/del_comment/", view= views.del_comment, name="del_comment"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brand.urls')),
    path('find/', include('map.urls')),
    path('user/', include('user.urls')),
    path('LnF/', include('LnF.urls')),
    path('accounts/', include('allauth.urls')),

    path('', include('django.contrib.auth.urls')),
    
    #템플릿 추가중
    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='user/reset_password.html'),
        name='password_reset'
    ),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='user/reset_password_sent.html'), name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='user/reset_password_form.html'),
        name='password_reset_confirm'
    ),

    path(
        'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='user/reset_password_sucess.html'),
        name='password_reset_complete'
    ),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),

]
#set image urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

map/urls.py
from django.urls import path
from map import views

app_name = "map"

urlpatterns = [
    path('booth/review/create/<int:pk>', view=views.booth_review_create, name='booth_review_create'),  # 리뷰 작성/수정 페이지
    path('<int:pk>/update', view=views.review_update, name='review_update'),
    path('<int:pk>/delete', view=views.review_delete, name='review_delete'),

    path('booth/detail/<int:pk>', view=views.booth_detail, name='booth_detail'),
    path('booth/detail/<int:pk>/review', view=views.booth_review_list, name='booth_review_list'),
    path('booth/detail/<int:pk>/like_ajax/', views.like_ajax, name='like_ajax'),
    path('booth/detail/<int:pk>/dislike_ajax/', views.dislike_ajax, name='dislike_ajax'),

    path('', view= views.mainpage, name = 'main'), # 메인페이지 view
    path('map/', views.mymap, name="mymap"),
    path('search/', views.search, name="search"),
    path('map/load/', view=views.load, name='load')
]

user/urls.py
from django.urls import path
from . import views

# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "user"

urlpatterns = [
    path("", views.main, name="main"),
    path("my_lnf/", views.my_lnf, name="my_lnf"),
    path('read_my_lnf/<int:pk>', views.read_my_lnf, name="read_my_lnf"),
    path("my_review/", views.my_review, name="my_review"),
    path('read_my_review/<int:pk>', views.read_my_review, name="read_my_review"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="log_out"),
    path("signup/", views.signup, name="signup"),
    path("change_password/", views.change_password, name='change_password'),
    path('modify/', views.modify, name='modify'),

    path('delete/', views.delete, name='delete'),
    path('notice/', views.notice, name="notice"),
    path('readnotice/<int:pk>', views.read_notice, name="read_notice"),
    path('notice/deletenotice/', views.delete_notice, name="delete_notice"),
    path('nav_notice/', views.nav_notice, name="nav_notice"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/star.css' %}"> 
    <link rel="shortcut icon" href="{% static 'icons/favicon.ico'%}"/>
    <script defer src="{% static 'js/notice.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0,maximum-scale=1.0, user-scalable=no">
    <!-- remixicon css -->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    {% block head %}
    {% endblock %}

    <title>여기사진</title>
</head>

<body>
  
    <nav class="navbar bg-light sticky-top">
      <div class="container-fluid" style="color: #1F52FF;">
        <!-- hamburger btn -->
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target=".header__navbar">
          <i class="ri-menu-fill mobile-nav-toggle" style="color: #1F52FF;"></i>
        </button>
        <!-- title 구간 -->
        <div>
          <a class="header__title" href="/">여기사진</a> 
        </div>
        <!-- user 구간 -->
        <div>
          <button class="navbar-toggler" type="button">
            {% if user.is_authenticated %} 
              <a class="position-relative" href="{% url 'user:main' %}"><i class="ri-user-line position-relative" style="color: #1F52FF;" ></i></a>
            {% else %}
              <a href="{% url 'user:login' %}"><i class="ri-login-circle-line" style="color: #1F52FF;"></i></a>
            {% endif %}
          </button>
        </div> 
        <!-- navbar list -->
        <div class="header__navbar navbar-collapse collapse">
          <ul class="navbar-nav me-auto mb-2 mb-xl-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">홈</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'map:mymap' %}">매장찾기</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'LnF:list' %}">분실물찾기</a>
            </li>
          </ul>
        </div>      
      </div>
    </nav>

    {% block header %}
    {% endblock %}

    <!-- main block -->
    {% block content %}
    {% endblock %}
    
</body>
</html>