LnF/urls.py
from django.urls import path
from LnF import views

app_name = "LnF"

urlpatterns = [
    path("", view=views.list, name='list'),
    path("new/", view=views.new, name='new'),
    path("new/<int:pk>", view=views.new_one, name='new_one'),
    path("tag/", view=views.tag, name='tag'),
    path("<int:pk>/booth_detail/", view=views.booth_detail, name='booth_detail'),
    path("<int:pk>/post_detail/", view=views.post_detail, name='post_detail'),
    path("<int:pk>/update/", view=views.post_update, name='post_update'),
    path("<int:pk>/delete/", view=views.post_delete, name='post_delete'),
    path("<int:pk>/post_detail/add_comment/", view= views.add_comment, name="add_comment"),
    path("<int:pk>/post_detail/del_comment/", view= views.del_comment, name="del_comment"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brand.urls')),
    path('find/', include('map.urls')),
    path('user/', include('user.urls')),
    path('LnF/', include('LnF.urls')),
    path('accounts/', include('allauth.urls')),

    path('', include('django.contrib.auth.urls')),
    
    #템플릿 추가중
    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='user/reset_password.html'),
        name='password_reset'
    ),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='user/reset_password_sent.html'), name='password_reset_done'),

    path(
        'password_reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='user/reset_password_form.html'),
        name='password_reset_confirm'
    ),

    path(
        'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='user/reset_password_sucess.html'),
        name='password_reset_complete'
    ),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),

]
#set image urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

map/urls.py
from django.urls import path
from map import views

app_name = "map"

urlpatterns = [
    path('booth/review/create/<int:pk>', view=views.booth_review_create, name='booth_review_create'),  # 리뷰 작성/수정 페이지
    path('<int:pk>/update', view=views.review_update, name='review_update'),
    path('<int:pk>/delete', view=views.review_delete, name='review_delete'),

    path('booth/detail/<int:pk>', view=views.booth_detail, name='booth_detail'),
    path('booth/detail/<int:pk>/review', view=views.booth_review_list, name='booth_review_list'),
    path('booth/detail/<int:pk>/like_ajax/', views.like_ajax, name='like_ajax'),
    path('booth/detail/<int:pk>/dislike_ajax/', views.dislike_ajax, name='dislike_ajax'),

    path('', view= views.mainpage, name = 'main'), # 메인페이지 view
    path('map/', views.mymap, name="mymap"),
    path('search/', views.search, name="search"),
    path('map/load/', view=views.load, name='load')
]

user/urls.py
from django.urls import path
from . import views

# 비번 초기화
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "user"

urlpatterns = [
    path("", views.main, name="main"),
    path("my_lnf/", views.my_lnf, name="my_lnf"),
    path('read_my_lnf/<int:pk>', views.read_my_lnf, name="read_my_lnf"),
    path("my_review/", views.my_review, name="my_review"),
    path('read_my_review/<int:pk>', views.read_my_review, name="read_my_review"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="log_out"),
    path("signup/", views.signup, name="signup"),
    path("change_password/", views.change_password, name='change_password'),
    path('modify/', views.modify, name='modify'),

    path('delete/', views.delete, name='delete'),
    path('notice/', views.notice, name="notice"),
    path('readnotice/<int:pk>', views.read_notice, name="read_notice"),
    path('notice/deletenotice/', views.delete_notice, name="delete_notice"),
    path('nav_notice/', views.nav_notice, name="nav_notice"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    user_liked = models.IntegerField(verbose_name="liked",default=0)

user/forms.py
from django import forms
from .models import User

#세션의 폼 그대로 사용했습니다.
class LoginForm(forms.Form):
    username = forms.CharField(max_length=40)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        email = self.cleaned_data.get("email")

        try:
            user = User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                raise forms.ValidationError("비밀번호가 틀렸습니다.")
        except User.DoesNotExist:
            raise forms.ValidationError("존재하지 않는 유저입니다.")

class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

user/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from django.contrib.auth import authenticate, login, logout
from django.views import View
from .forms import LoginForm, SignupForm
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
# 탈퇴시 랜덤숫자를 위해
from random import randint

# 리뷰 가져오기
from LnF.models import *

#Liked 구현 
from map.models import *

from django.contrib.auth.decorators import login_required

import json

# AnonymousUser 예외처리
@login_required
def main(request):
    users = request.user

    # dolike가 true인 booth-brand pair 관련 list 만들기
    liked_booth_brand = []
    my_likes = Liked.objects.filter(user = users)
    for my_like in my_likes:
        if my_like.dolike:
            liked_booth_brand.append([my_like.booth, my_like.booth.brand])

    user_liked_num = len(liked_booth_brand)
    comments = getNew(users)
    ctx = {'len': len(comments), 'liked_booth_brand':liked_booth_brand, 'user_liked_num': user_liked_num}
    return render(request, 'user/main.html', context=ctx)

@login_required
def my_review(request):
    users = request.user

    #리뷰
    reviews_posts = Review.objects.filter(user = users)

    try:
        my_review_exist = Review.objects.get(user = users)
    except Review.DoesNotExist:
        my_review_exist = 0
    except Review.MultipleObjectsReturned:
        my_review_exist = 1
    
    ctx = {'reviews_posts': reviews_posts,'my_review_exist': my_review_exist}
    return render(request, 'user/my_review.html', context=ctx)

def read_my_review(request, pk):
    my_review = Review.objects.get(pk=pk)

    return redirect('map:review_detail', my_review.id)

@login_required
def my_lnf(request):
    users = request.user

    #분실물
    lnf_posts = LnF_Post.objects.filter(user = users)

    try:
        my_lnf_exist = LnF_Post.objects.get(user = users)
    except LnF_Post.DoesNotExist:
        my_lnf_exist = 0
    except LnF_Post.MultipleObjectsReturned:
        my_lnf_exist = 1

    ctx = {'lnf_posts': lnf_posts, 'my_lnf_exist': my_lnf_exist}
    return render(request, 'user/my_lnf.html', context=ctx)

def read_my_lnf(request, pk):
    my_lnf = LnF_Post.objects.get(pk=pk)

    return redirect('LnF:post_detail', my_lnf.id)

class LoginView(View):
    @method_decorator(csrf_exempt)
    def get(self, request):
        form = LoginForm()
        return render(request, "user/login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password, email=email)
            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend') #아래와 동일. 
                return redirect("user:main")

            return render(request, "user/login.html")

        ctx = {"form": form}
        return render(request, "user/login.html", ctx)

def log_out(request):
    logout(request)
    return redirect("/")

def signup(request):
    form = SignupForm()
    if request.method == "POST":
        if User.objects.filter(username = request.POST['username']).exists():
            help_text = '이미 존재하는 아이디입니다.'
        elif request.POST['password1'] != request.POST['password2']:
            help_text = '비밀번호가 일치하지 않습니다'
        elif User.objects.filter(email = request.POST['email']).exists():
            help_text = '이미 존재하는 이메일입니다.'
        else :
            user = User.objects.create_user(
                username = request.POST['username'],
                password = request.POST['password1'],
                email = request.POST['email'],
            )
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            #login(request, user) #바로 로그인 -> 소셜 로그인 구현으로 인한 백엔드 오류 방지
            return redirect ('user:main')
        ctx = {'help_text':help_text}
        return render(request, template_name='user/signup.html',context=ctx)
    else:
        form = SignupForm()
        ctx = {'form':form}
        return render(request, template_name='user/signup.html', context=ctx)

# 패스워드 변경
from django.contrib.auth.hashers import check_password
from django.contrib import messages, auth

@login_required
def change_password(request):
  if request.method == "POST":
    user = request.user
    # 아이디 변경
    edit_username = request.GET.get('edit_username', user.username)
    # edit_username = request.POST["username"]
    print(edit_username)
    # 패스워드 조건 설정
    origin_password = request.POST["origin_password"]

    if check_password(origin_password, user.password):
      new_password = request.POST["new_password"]
      confirm_password = request.POST["confirm_password"]
      if new_password == confirm_password:
        user.set_password(new_password)
        user.save()
        auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('user:main')
      else:
        messages.error(request, '비밀번호가 일치하지 않습니다.')
    else:
      messages.error(request, '현재 비밀번호가 일치하지 않습니다.')
    return render(request, 'user/change_password.html')
  else:
    return render(request, 'user/change_password.html')

@login_required
def modify(request):
    if request.method == "POST":
        user = request.user
        user.username = request.POST["username"]
        user.email = request.POST["email"]
        print(user.username)
        print(user.email)
        user.save()
        
        return redirect('user:main')
    return render(request, 'user/modify.html')

@login_required
def delete(request):
    if request.method == "POST":
        user = request.user
        pw_del = request.POST["pw_del"]
        if check_password(pw_del, user.password):
            random_number = randint(1000, 10000)
            user.username = "탈퇴한 사용자"+str(random_number)
            user.password = randint(1000000000, 10000000000)
            user.save()
            logout(request)
            # user.delete()
            return redirect('/')
        else:
            messages.error(request, '현재 비밀번호가 일치하지 않습니다.')
    return render(request, 'user/delete.html')

def notice(request):
    comments = getNew(request.user)
    ctx={'comments':comments, 'len':len(comments)}

    return render(request, template_name='user/notice.html', context=ctx)

def getNew(userss):
    posts = LnF_Post.objects.filter(user=userss)
    comments =  Comment.objects.none()
    for post in posts:
        comments = comments | post.comment_set.filter(read=0)
    return comments

@login_required
def read_notice(request, pk):
    try:
        comment = get_object_or_404(Comment, pk=pk)
    except:
        return render(request, 'account/login.html')

    comment.read = 1
    comment.save()

    return redirect('LnF:post_detail', comment.post.id)

@login_required
@csrf_exempt
def delete_notice(request):
    req = json.loads(request.body)
    notice_id = req['id']
    try:
        comment = get_object_or_404(Comment, pk=notice_id)
    except:
        return render(request, 'account/login.html')

    comment.read = 1
    comment.save()

    remain = len(getNew(request.user))
    print("\n\n", notice_id, remain)
    return JsonResponse({'deleted_id': notice_id, 'remain': remain})


def nav_notice(request):
    if request.user.is_authenticated:
        comments = getNew(request.user)
        notice_num = len(comments)
        if len(comments) > 0:
            notice = True
        else:
            notice = False
        
    else:
        notice =False
        notice_num = 0
        
    ctx={'notice': notice, 'notice_num': notice_num}
    return JsonResponse(ctx)

templates/user/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/user/signup.css' %}">
{% endblock %}

{% block content %}
<div class="title__all">
  <h2 class="signup__title">Change<span class="signup__title__bold">Password</span></h2>
  <p class="space signup__subtitle">새로운 비밀번호를 생성해주세요.</p>
</div>
{% if messages %}
{% for message in messages %}
<div class="row" style="margin:20px auto;">
  <div class="col-sm-12">
    <div class="alert alert-danger">
      <strong>{{ message.tags }}!</strong> {{ message.message }}
    </div>
  </div>
</div>
{% endfor %}
{% endif %}
<div class="center__form">
  <form method="POST" action="{% url 'user:change_password' %}">
    {% csrf_token %}
    <p class="top__text">ORIGIN PASSWORD</p>
    <div class="form-group">
      <input class="form-field"name="origin_password" type="password" placeholder="Origin Password" required>
    </div>

    <p class="top__text">NEW PASSWORD</p>
    <div class="form-group">
      <input class="form-field" name="new_password" type="password" placeholder="New Password" required>
    </div>
    
    <p class="top__text">CONFIRM PASSWORD</p>
    <div class="form-group">
      <input class="form-field" name="confirm_password" type="password" placeholder="Confirm Password" required>
    </div>

    <div class="bottom__btn">
      <input class="signup__input btn btn-primary" type="submit" value="Change">
    </div>
  </form>
</div>

{% endblock %}

templates/user/delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/user/delete.css' %}">
{% endblock %}

{% block content %}
<div class="title__all">
    <h2 class="signup__title">Bye,<span class="signup__title__light">{{ user }}👋</span></h2>
  
    <p class="signup__subtitle">정말로 떠나실껀가요?🥺</p>
    <p class="space__alert signup__subtitle">ㅇㄱㅅㅈ에서 기록한 모든 것이 사라집니다</p>
</div>
{% if messages %}
{% for message in messages %}
<div class="row" style="margin:20px auto;">
    <div class="col-sm-12">
        <div class="alert alert-danger">
            <strong>{{ message.tags }}!</strong> {{ message.message }}
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
<div class="center__form">
    <form action="{% url 'user:delete' %}" method="POST">
        {% csrf_token %}
        <p class="top__text">CONFIRM PASSWORD</p>
        <div class="form__all">
            <div class="form-group">
                <input class="form-field" type="text" name="pw_del" placeholder="confirm Password" required>
            </div>
        </div>
        <div class="bottom__btn">
            <input class="signup__input btn btn-primary" type="submit" value="회원탈퇴">
        </div>
    </form>
</div>

{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% load static %}
{% load socialaccount %}

{% providers_media_js %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/user/login.css' %}">
{% endblock %}

{% block content %}
<div class="title__all">
    <h2 class="signup__title">Welcome<span class="signup__title__bold">Back!</span></h2>
  
    <p class="signup__subtitle">Enter your informations below</p>
    <p class="space signup__subtitle">or login with a social account</p>
</div>
<div class="login__form center__form ">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_table}}
        <div class="bottom__btn">
            <button>Login</button>
        </div>
    </form>
</div>
<div class="signup__btn">
    <a class="signup" href="{% url 'user:signup' %}">Sign up</a>
</div>
<div class="hr-sect">OR</div>

<div class="social__btn">
    <div class="social__flex social">
        <img class="icon__social" src="{% static 'icons/google_logo.png' %}">
        <a class="social__text" href="{% provider_login_url "google" %}">Login with Google</a>
    </div>
</div>
<div class="social__btn">
    <div class="social__flex social">
        <img class="icon__social" src="{% static 'icons/naver_logo.png' %}">
        <a class="social__Text" href="{% provider_login_url "naver" %}">Login with Naver</a>
    </div>

    
</div>

<a class="password" href="{% url 'password_reset' %}">Forgot password?</a>


{% endblock content %}

templates/user/main.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/user/style.css' %}">
{% endblock %}

{% block content %}
<div>
    {% if user.is_authenticated %}
    <div class="all">
        <div class="profile">
            <h3>{{ user }}</h3>
            <h4>{{ user }}님! 여기사진과 함께</h4>
            <h4>다양한 부스를 방문해보세요😉</h4>
        </div>
        <div class="part">
            <p class="sub__title">liked</p>
            {% if user_liked_num == 0 %}
            <p class="no__liked">계정의 첫 좋아요를 남겨보세요🥳 </p>
            {% else %}
            <div class="liked_container ">    
                {% for booth_brand in liked_booth_brand %}
                <div class="liked__content">
                    <img class="liked__img" src="{{booth_brand.1.liked_img}}" alt="">
                    <p class="liked__title">{{booth_brand.0.name}}</p>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            
        </div>
        <div class="part">
            <p class="sub__title">Dashboard</p>
            <div>
                <div class="line"><img src="{% static 'icons/LnF.svg' %}"><a href="{% url 'user:my_lnf' %}">Lost and Found</a><span class="space__1"></span><a class="arrow" href="{% url 'user:my_lnf' %}">><span class="space"></span></a></div>      
                <div class="line"><img src="{% static 'icons/review.svg' %}"><a href="{% url 'user:my_review' %}">Reviews</a><span class="space__2"></span><a class="arrow" href="{% url 'user:my_review' %}">><span class="space"></span></a></div></a>
                <div class="line"><img src="{% static 'icons/notice.svg' %}">
                {% if len != 0 %}
                    <a href="{% url 'user:notice' %}">Notice</a><span class="space__notice"></span><a class="arrow" href="{% url 'user:notice' %}"><span class="notice">{{ len }} New ><span></a>
                {% else %}
                    <a href="{% url 'user:notice' %}">Notice</a><span class="space__3"></span><a class="arrow" href="{% url 'user:notice' %}">><span class="space"></span></a>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="part">
            <p class="sub__title">My account</p>
            <div class="log__out"><a href="{% url 'user:log_out' %}">log out</a></div>
            <div class="edit"><a href="{% url 'user:modify' %}">Edit profile</a></div>
        </div>
    </div>
    
    {% else %}
    <a href="{% url 'user:login' %}">로그인</a>
    {% endif %}

    
</div>
{% endblock%}

templates/user/modify.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/user/modify.css' %}">
{% endblock %}

{% block content %}
    <div class="profile">
        <div class="username">{{ user }}</div>
        <div class="description">{{ user }}님! 여기사진과 함께 </div>
        <div class="description">다양한 부스를 방문해보세요😉</div>
    </div>
    <div class="center__form">
        <form action="{% url 'user:modify' %}" method="POST">
            {% csrf_token %}
            <p class="top__text">EMAIL</p>
            <div class="form-group">
                <input class="form-field" type="email" name="email" value="{{ user.email }}" required>
            </div>
    
            <p class="top__text">USERNAME</p>
            <div class="form-group">
                <input class="form-field" type="text" name="username" value="{{ user.username }}">
            </div>
            <div class="bottom__btn">
                <input class="signup__input" type="submit" value="회원수정">
            </div>
            
        </form>
    </div>
    <div class="bottom__btn space">
        <a class="password" href="{% url 'user:change_password' %}">패스워드 변경</a>
    </div>

    <div class="bottom__text">
        <a class="out" href="{% url 'user:delete' %}">회원탈퇴</a>
    </div>
{% endblock %}

templates/user/my_review.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/user/my_review.css' %}">
    <script defer src="{% static 'js/map/imgmodal.js' %}"></script>
{% endblock %}


{% block content %}
<section class = "my_review">
    <p class="sub__title">My review</p>
    {% if my_review_exist == 0 %}
        <div class="no__post">게시물이 없습니다.</div>
    {% else %}
    {% for review in reviews_posts %}
    <div class = "review">
        <div class="reviewblock">
            <a href = "{% url 'map:booth_detail' review.boothid %}">
                <div class="head">
                    <div class ='title' onclick="location.href='{% url 'map:booth_detail' review.boothid %}'">
                    {{review.booth}}
                    </div>
                    <div class="container-drop">
                        <div class="dropdown">
                            <a class="btn btn-sm btn-outline-none dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">⋮</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                {% if review.user == request.user %}
                            <li><a class="dropdown-item" href="{% url 'map:review_update' review.id %}">수정</a></li>
                            <li><a class="dropdown-item" onclick="post_del({{post.id}})">삭제</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="container">
                    {% if review.img %}
                    <div class="content col-7" onclick="location.href='{% url 'map:booth_detail' review.boothid %}'">
                        <div class="text">
                            {{review.content}}
                        </div>
                        <div class="color">
                            <div class ="colortext" style="width:40px">배경색 : </div>
                            {% for color in review.color %}
                            {% if color == '핑크'%}<div><button type="button" class="colorbtn colorpink">■</button></div>
                            {% elif color == '하늘'%}<div><button type="button" class="colorbtn colorskyblue">■</button></div>
                            {% elif color == '노랑'%}<div><button type="button" class="colorbtn coloryellow">■</button></div>
                            {% elif color == '회색'%}<div><button type="button" class="colorbtn colorgray">■</button></div>
                            {% elif color == '남색'%}<div><button type="button" class="colorbtn colorindigo">■</button></div>
                            {% elif color == '연두'%}<div><button type="button" class="colorbtn colorgreen">■</button></div>
                            {% elif color == '보라'%}<div><button type="button" class="colorbtn colorpurple">■</button></div>
                            {% elif color == '빨강'%}<div><button type="button" class="colorbtn colorred">■</button></div>
                            {% elif color == '주황'%}<div><button type="button" class="colorbtn colororange">■</button></div>
                            {% elif color == '기타'%}<div><button type="button" class="colorbtn colorrainbow">■</button></div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="imgcontent col-5">
                        <img src="{{ review.img.url }}" class="img" width="100%">
                        <div class="modal">
                          <span class="close"></span>
                          <img src= "{{ review.img.url }}" class="modal-content">
                        </div>
                    </div>
                    {% else %}
                    <div  onclick="location.href='{% url 'map:booth_detail' review.boothid %}'">
                        <div class="text">
                            {{review.content}}
                        </div>
                        <div class="color">
                            <div class ="colortext" style ="width: 40px">배경색 : </div>
                            {% for color in review.color %}
                                {% if color == '핑크'%}<div><button type="button" class="colorbtn colorpink">■</button></div>
                                {% elif color == '하늘'%}<div><button type="button" class="colorbtn colorskyblue">■</button></div>
                                {% elif color == '노랑'%}<div><button type="button" class="colorbtn coloryellow">■</button></div>
                                {% elif color == '회색'%}<div><button type="button" class="colorbtn colorgray">■</button></div>
                                {% elif color == '남색'%}<div><button type="button" class="colorbtn colorindigo">■</button></div>
                                {% elif color == '연두'%}<div><button type="button" class="colorbtn colorgreen">■</button></div>
                                {% elif color == '보라'%}<div><button type="button" class="colorbtn colorpurple">■</button></div>
                                {% elif color == '빨강'%}<div><button type="button" class="colorbtn colorred">■</button></div>
                                {% elif color == '주황'%}<div><button type="button" class="colorbtn colororange">■</button></div>
                                {% elif color == '기타'%}<div><button type="button" class="colorbtn colorrainbow">■</button></div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                </div>
                <div class="container_review" onclick="location.href='{% url 'map:booth_detail' review.boothid %}'">
                        <div class="star-rating">
                            <div class="star-rating-fill" style= "width: {{review.getWidth}}%;">
                                <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                            </div>
                            <div class="star-rating-base">
                                <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                            </div>
                        </div>
                </div>
                <div class = "tag" onclick="location.href='{% url 'map:booth_detail' review.boothid %}'">
                    {% for tag in review.tag %}
                        {% if tag == '시설이 깨끗해요'%}<div class="tagbtn">✨ 시설이 깨끗해요</div>
                        {% elif tag == '소품이 다양해요'%}<div class="tagbtn">🎉  소품이 다양해요</div>
                        {% elif tag == '부스가 많아요'%}<div  class="tagbtn">📸 부스가 많아요</div>
                        {% elif tag == '고데기가 있어요'%}<div class="tagbtn">💇🏻‍ 고데기가 있어요</div>
                        {% elif tag == '로드점이에요'%}<div class="tagbtn">🛣️ 로드점이에요</div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="time" onclick="location.href='{% url 'map:booth_detail' review.boothid %}'">
                    <div class="foot">
                        {{review.user}} | {{review.time|date:'m월 d일'}}
                    </div>
                </div>
            </a>
        </div>
    </div>
    <script>
        const post_del = (id) => {
        var res = confirm('정말로 삭제하시겠습니까?');
        if (res){
            window.location.href = "{% url 'map:review_delete' review.id %}"
            alert('성공적으로 삭제되었습니다.')
        }
    }
    </script>
        {% endfor %}

    {% endif %}
</section>
{% endblock %}

templates/user/reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/user/reset_password.css' %}">
{% endblock %}

{% block content %}
<body>
  <div class="title__all">
    <h2 class="signup__title">Reset<span class="signup__title__bold">Password</span></h2>
  
    <p class="signup__subtitle">아래에 계정과 연결된 이메일 주소를 적어주세요.</p>
    <p class="space signup__subtitle">새로운 비밀번호 설정을 위한 메일을 보내드립니다.</p>
  </div>
  
  <div class="reset__form center__form">
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="bottom__btn">
        <button type="submit" value="메일 보내기">Send email</button>
      </div>
    </form>
  </div>
</body>

{% endblock %}